
-- Generated by ORDS REST Data Services 24.3.2.r3121009
-- Schema: ORDSDEMO  Date: Tue Dec 31 04:38:48 2024 
--
        
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => '[Your username/schema]',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => '[same as p_schema in all lowercase]',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ords_and_jotform',
      p_base_path      => '/oj/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_varchar2s',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_varchar2s',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    incoming_payload CLOB;
BEGIN
    incoming_payload := :body_json;
    INSERT INTO JOTFORM_VARCHAR2S values(
        JSON_VALUE(incoming_payload, ''$.type''),
        JSON_VALUE(incoming_payload, ''$.ip''),
        JSON_VALUE(incoming_payload, ''$.formTitle''),
        JSON_VALUE(incoming_payload, ''$.webhookURL''),
        JSON_VALUE(incoming_payload, ''$.rawRequest''),
        JSON_VALUE(incoming_payload, ''$.submissionID''),
        JSON_VALUE(incoming_payload, ''$.username''),
        JSON_VALUE(incoming_payload, ''$.formID''),
        JSON_VALUE(incoming_payload, ''$.pretty'')
    );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_clobs',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_clobs',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
BEGIN
    INSERT INTO JOTFORM_CLOBS values(
        :type,
        :ip,
        :formTitle,
        :webhookURL,
        :rawRequest,
        :submissionID,
        :username,
        :formID,
        :pretty
    );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_data',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords_and_jotform',
      p_pattern        => 'jotform_data',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    incoming_payload CLOB;
BEGIN
    incoming_payload := :body_json;
    INSERT INTO JOTFORM_DATA VALUES ( :content_type,
                                      incoming_payload );

END;');

        
COMMIT;

END;