CREATE TABLE JOTFORM_DATA 
    ( 
     CONTENT_TYPE VARCHAR2 (4000) , 
     PAYLOAD      VARCHAR2 (4000) 
    ) 
;

-- CREATE TABLE ORDSDEMO.JOTFORM_CLOBS 
    ( 
     FORMTYPE     CLOB , 
     IP           CLOB , 
     FORMTITLE    CLOB , 
     WEBHOOKURL   CLOB , 
     RAWREQUEST   CLOB , 
     SUBMISSIONID CLOB , 
     USERNAME     CLOB , 
     FORMID       CLOB , 
     PRETTY       CLOB 
    ) 
;

CREATE TABLE ORDSDEMO.JOTFORM_VARCHAR2S 
    ( 
     FORMTYPE     VARCHAR2 (4000) , 
     IP           VARCHAR2 (4000) , 
     FORMTITLE    VARCHAR2 (4000) , 
     WEBHOOKURL   VARCHAR2 (4000) , 
     RAWREQUEST   VARCHAR2 (4000) , 
     SUBMISSIONID VARCHAR2 (4000) , 
     USERNAME     VARCHAR2 (4000) , 
     FORMID       VARCHAR2 (4000) , 
     PRETTY       VARCHAR2 (4000) 
    ) 
;