-- Generated by ORDS REST Data Services 23.4.0.r3361940
-- Schema: ORDSTEST  Date: Thu Dec 07 07:14:37 2023 

-- *** Replace with your schema (where applicable) ***   

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ORDSTEST',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ordstest',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'react.module',
      p_base_path      => '/api/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'react.module',
      p_pattern        => 'example/api/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

-- This sql is also in the sqlscript.sql file. It this the FIRST SQL query!

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'react.module',
      p_pattern        => 'example/api/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select ename, dname, job, empno, hiredate, loc   
from emp, dept   
where emp.deptno = dept.deptno   
order by ename');

    
        
COMMIT;

END;