
-- Generated by ORDS REST Data Services 23.3.0.r2891830
-- Schema: ORDSTEST  Date: Tue Nov 14 12:05:21 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ORDSTEST',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ordstest',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ords.perf.test',
      p_base_path      => '/perftest/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'one/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'one/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
 dbms_session.sleep(1);
 :msg := ''Slept for 1 second.'';
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ords.perf.test',
      p_pattern            => 'one/',
      p_method             => 'GET',
      p_name               => 'Response message',
      p_bind_variable_name => 'msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'onesevenfive/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'onesevenfive/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
 dbms_session.sleep(1.75);
 :msg := ''Slept for 1.75 seconds.'';
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ords.perf.test',
      p_pattern            => 'onesevenfive/',
      p_method             => 'GET',
      p_name               => 'Response message',
      p_bind_variable_name => 'msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'onefive/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ords.perf.test',
      p_pattern        => 'onefive/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
 dbms_session.sleep(1.5);
 :msg := ''Slept for 1.5 seconds.'';
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ords.perf.test',
      p_pattern            => 'onefive/',
      p_method             => 'GET',
      p_name               => 'Response message',
      p_bind_variable_name => 'msg',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

    
        
COMMIT;

END;