SET SERVEROUTPUT ON;
Begin
   Execute Immediate 'Grant ALTER SYSTEM to PDBADMIN';
   Execute Immediate 'Grant AUDIT SYSTEM to PDBADMIN';
   Execute Immediate 'Grant CREATE SESSION to PDBADMIN';
   Execute Immediate 'Grant ALTER SESSION to PDBADMIN';
   Execute Immediate 'Grant RESTRICTED SESSION to PDBADMIN';
   Execute Immediate 'Grant CREATE TABLESPACE to PDBADMIN';
   Execute Immediate 'Grant ALTER TABLESPACE to PDBADMIN';
   Execute Immediate 'Grant MANAGE TABLESPACE to PDBADMIN';
   Execute Immediate 'Grant DROP TABLESPACE to PDBADMIN';
   Execute Immediate 'Grant UNLIMITED TABLESPACE to PDBADMIN';
   Execute Immediate 'Grant CREATE USER to PDBADMIN';
   Execute Immediate 'Grant BECOME USER to PDBADMIN';
   Execute Immediate 'Grant ALTER USER to PDBADMIN';
   Execute Immediate 'Grant DROP USER to PDBADMIN';
   Execute Immediate 'Grant CREATE ROLLBACK SEGMENT to PDBADMIN';
   Execute Immediate 'Grant ALTER ROLLBACK SEGMENT to PDBADMIN';
   Execute Immediate 'Grant DROP ROLLBACK SEGMENT to PDBADMIN';
   Execute Immediate 'Grant CREATE TABLE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant LOCK ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant COMMENT ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant INSERT ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant UPDATE ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant DELETE ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant REDEFINE ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant CREATE CLUSTER to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY CLUSTER to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY CLUSTER to PDBADMIN';
   Execute Immediate 'Grant DROP ANY CLUSTER to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY INDEX to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY INDEX to PDBADMIN';
   Execute Immediate 'Grant DROP ANY INDEX to PDBADMIN';
   Execute Immediate 'Grant CREATE SYNONYM to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY SYNONYM to PDBADMIN';
   Execute Immediate 'Grant DROP ANY SYNONYM to PDBADMIN';
   Execute Immediate 'Grant CREATE PUBLIC SYNONYM to PDBADMIN';
   Execute Immediate 'Grant DROP PUBLIC SYNONYM to PDBADMIN';
   Execute Immediate 'Grant CREATE VIEW to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY VIEW to PDBADMIN';
   Execute Immediate 'Grant DROP ANY VIEW to PDBADMIN';
   Execute Immediate 'Grant CREATE SEQUENCE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY SEQUENCE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY SEQUENCE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY SEQUENCE to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY SEQUENCE to PDBADMIN';
   Execute Immediate 'Grant CREATE DATABASE LINK to PDBADMIN';
   Execute Immediate 'Grant CREATE PUBLIC DATABASE LINK to PDBADMIN';
   Execute Immediate 'Grant DROP PUBLIC DATABASE LINK to PDBADMIN';
   Execute Immediate 'Grant CREATE ROLE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY ROLE to PDBADMIN';
   Execute Immediate 'Grant GRANT ANY ROLE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY ROLE to PDBADMIN';
   Execute Immediate 'Grant AUDIT ANY to PDBADMIN';
   Execute Immediate 'Grant ALTER DATABASE to PDBADMIN';
   Execute Immediate 'Grant FORCE ANY TRANSACTION to PDBADMIN';
   Execute Immediate 'Grant CREATE PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant CREATE TRIGGER to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY TRIGGER to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY TRIGGER to PDBADMIN';
   Execute Immediate 'Grant DROP ANY TRIGGER to PDBADMIN';
   Execute Immediate 'Grant CREATE PROFILE to PDBADMIN';
   Execute Immediate 'Grant ALTER PROFILE to PDBADMIN';
   Execute Immediate 'Grant DROP PROFILE to PDBADMIN';
   Execute Immediate 'Grant ALTER RESOURCE COST to PDBADMIN';
   Execute Immediate 'Grant ANALYZE ANY to PDBADMIN';
   Execute Immediate 'Grant CREATE MATERIALIZED VIEW to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY MATERIALIZED VIEW to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY MATERIALIZED VIEW to PDBADMIN';
   Execute Immediate 'Grant DROP ANY MATERIALIZED VIEW to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY DIRECTORY to PDBADMIN';
   Execute Immediate 'Grant DROP ANY DIRECTORY to PDBADMIN';
   Execute Immediate 'Grant CREATE TYPE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY TYPE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY TYPE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY TYPE to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY TYPE to PDBADMIN';
   Execute Immediate 'Grant UNDER ANY TYPE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY LIBRARY to PDBADMIN';
   Execute Immediate 'Grant DROP ANY LIBRARY to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY LIBRARY to PDBADMIN';
   Execute Immediate 'Grant CREATE LOGICAL PARTITION TRACKING to PDBADMIN';
   Execute Immediate 'Grant DROP LOGICAL PARTITION TRACKING to PDBADMIN';
   Execute Immediate 'Grant CREATE OPERATOR to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY OPERATOR to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY OPERATOR to PDBADMIN';
   Execute Immediate 'Grant DROP ANY OPERATOR to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY OPERATOR to PDBADMIN';
   Execute Immediate 'Grant CREATE INDEXTYPE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY INDEXTYPE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY INDEXTYPE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY INDEXTYPE to PDBADMIN';
   Execute Immediate 'Grant UNDER ANY VIEW to PDBADMIN';
   Execute Immediate 'Grant QUERY REWRITE to PDBADMIN';
   Execute Immediate 'Grant GLOBAL QUERY REWRITE to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY INDEXTYPE to PDBADMIN';
   Execute Immediate 'Grant UNDER ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant CREATE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY DIMENSION to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY DIMENSION to PDBADMIN';
   Execute Immediate 'Grant DROP ANY DIMENSION to PDBADMIN';
   Execute Immediate 'Grant MANAGE ANY QUEUE to PDBADMIN';
   Execute Immediate 'Grant ENQUEUE ANY QUEUE to PDBADMIN';
   Execute Immediate 'Grant DEQUEUE ANY QUEUE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY CONTEXT to PDBADMIN';
   Execute Immediate 'Grant DROP ANY CONTEXT to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY OUTLINE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY OUTLINE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY OUTLINE to PDBADMIN';
   Execute Immediate 'Grant ADMINISTER RESOURCE MANAGER to PDBADMIN';
   Execute Immediate 'Grant ADMINISTER DATABASE TRIGGER to PDBADMIN';
   Execute Immediate 'Grant MERGE ANY VIEW to PDBADMIN';
   Execute Immediate 'Grant ON COMMIT REFRESH to PDBADMIN';
   Execute Immediate 'Grant EXEMPT ACCESS POLICY to PDBADMIN';
   Execute Immediate 'Grant RESUMABLE to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY DICTIONARY to PDBADMIN';
   Execute Immediate 'Grant DEBUG CONNECT SESSION to PDBADMIN';
   Execute Immediate 'Grant DEBUG CONNECT ANY to PDBADMIN';
   Execute Immediate 'Grant DEBUG ANY PROCEDURE to PDBADMIN';
   Execute Immediate 'Grant FLASHBACK ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant GRANT ANY OBJECT PRIVILEGE to PDBADMIN';
   Execute Immediate 'Grant CREATE EVALUATION CONTEXT to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY EVALUATION CONTEXT to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY EVALUATION CONTEXT to PDBADMIN';
   Execute Immediate 'Grant DROP ANY EVALUATION CONTEXT to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY EVALUATION CONTEXT to PDBADMIN';
   Execute Immediate 'Grant CREATE RULE SET to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY RULE SET to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY RULE SET to PDBADMIN';
   Execute Immediate 'Grant DROP ANY RULE SET to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY RULE SET to PDBADMIN';
   Execute Immediate 'Grant CREATE RULE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY RULE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY RULE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY RULE to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY RULE to PDBADMIN';
   Execute Immediate 'Grant ANALYZE ANY DICTIONARY to PDBADMIN';
   Execute Immediate 'Grant ADVISOR to PDBADMIN';
   Execute Immediate 'Grant CREATE JOB to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY JOB to PDBADMIN';
   Execute Immediate 'Grant MANAGE SCHEDULER to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY TRANSACTION to PDBADMIN';
   Execute Immediate 'Grant DROP ANY SQL PROFILE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY SQL PROFILE to PDBADMIN';
   Execute Immediate 'Grant ADMINISTER SQL TUNING SET to PDBADMIN';
   Execute Immediate 'Grant ADMINISTER ANY SQL TUNING SET to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY SQL PROFILE to PDBADMIN';
   Execute Immediate 'Grant READ ANY FILE GROUP to PDBADMIN';
   Execute Immediate 'Grant CHANGE NOTIFICATION to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY EDITION to PDBADMIN';
   Execute Immediate 'Grant DROP ANY EDITION to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY EDITION to PDBADMIN';
   Execute Immediate 'Grant CREATE ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant DROP ANY ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ANY ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant EXECUTE ASSEMBLY to PDBADMIN';
   Execute Immediate 'Grant CREATE MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant DROP ANY MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant COMMENT ANY MINING MODEL to PDBADMIN';
   Execute Immediate 'Grant CREATE CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant DELETE ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant DROP ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant INSERT ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant CREATE CUBE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY CUBE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY CUBE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY CUBE to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY CUBE to PDBADMIN';
   Execute Immediate 'Grant UPDATE ANY CUBE to PDBADMIN';
   Execute Immediate 'Grant CREATE MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant DELETE ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant DROP ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant INSERT ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant CREATE CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant DROP ANY CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant UPDATE ANY CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant UPDATE ANY CUBE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant ADMINISTER SQL MANAGEMENT OBJECT to PDBADMIN';
   Execute Immediate 'Grant CREATE SQL TRANSLATION PROFILE to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY SQL TRANSLATION PROFILE to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY SQL TRANSLATION PROFILE to PDBADMIN';
   Execute Immediate 'Grant DROP ANY SQL TRANSLATION PROFILE to PDBADMIN';
   Execute Immediate 'Grant KEEP DATE TIME to PDBADMIN';
   Execute Immediate 'Grant KEEP SYSGUID to PDBADMIN';
   Execute Immediate 'Grant PURGE DBA_RECYCLEBIN to PDBADMIN';
   Execute Immediate 'Grant EXEMPT REDACTION POLICY to PDBADMIN';
   Execute Immediate 'Grant TRANSLATE ANY SQL to PDBADMIN';
   Execute Immediate 'Grant CREATE PLUGGABLE DATABASE to PDBADMIN';
   Execute Immediate 'Grant SET CONTAINER to PDBADMIN';
   Execute Immediate 'Grant CREATE LOCKDOWN PROFILE to PDBADMIN';
   Execute Immediate 'Grant DROP LOCKDOWN PROFILE to PDBADMIN';
   Execute Immediate 'Grant ALTER LOCKDOWN PROFILE to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY MEASURE FOLDER to PDBADMIN';
   Execute Immediate 'Grant SELECT ANY CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY CUBE BUILD PROCESS to PDBADMIN';
   Execute Immediate 'Grant READ ANY TABLE to PDBADMIN';
   Execute Immediate 'Grant CREATE ATTRIBUTE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY ATTRIBUTE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY ATTRIBUTE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant DROP ANY ATTRIBUTE DIMENSION to PDBADMIN';
   Execute Immediate 'Grant CREATE HIERARCHY to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY HIERARCHY to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY HIERARCHY to PDBADMIN';
   Execute Immediate 'Grant DROP ANY HIERARCHY to PDBADMIN';
   Execute Immediate 'Grant CREATE ANALYTIC VIEW to PDBADMIN';
   Execute Immediate 'Grant CREATE ANY ANALYTIC VIEW to PDBADMIN';
   Execute Immediate 'Grant ALTER ANY ANALYTIC VIEW to PDBADMIN';
   Execute Immediate 'Grant DROP ANY ANALYTIC VIEW to PDBADMIN';

Exception
   when Others Then
   dbms_output.put_line('Failed grant statement: ' || sqlerrm || sqlcode ||'.');

End;
/